### ISSUE TITLE
Add a class system for players in the session

### ISSUE THREAD

**Issue by haykam821** [belguawhale/Discord-Werewolf#16]
The current system is messy, and @belguawhale has already said that the desperation totem pull request (#10) will not be merged until the bot is rewritten using classes instead of this garbage:

```
[True, {'285901641188769792': [True, 'villager', '', [], []], '2': [True, 'villager', '', [], []], '1': [True, 'seer', '', [], []], '193692127597821952': [True, 'wolf', '', [], []]}, False, [0, 0], [datetime.timedelta(0), datetime.timedelta(0)], datetime.datetime(2017, 6, 14, 22, 58, 44, 629421), 'default', {'wolf': 1, 'villager': 2, 'seer': 1}, '']
```

**Comment by belguawhale** [comment]
I'm learning how to use classes right now with a different bot; a rewrite has been planned for some time
