### ISSUE TITLE
Dependencies for project

### ISSUE THREAD

**Issue by unreturnable** [belguawhale/Discord-Werewolf#4]
I'm trying to set this up for a server of mine and I've hit the issue of the dependencies weren't shipped with the project and where to get them isn't listed.

**Comment by belguawhale** [comment]
Sorry, the current dependencies are aiohttp and discord.py. I will add a requirements.txt.

**Comment by unreturnable** [comment]
Thank you. It probably just be best to include it in the Readme file as setup instructions

**Comment by unreturnable** [comment]
I installed discord.py with the instructions found [here](https://github.com/Rapptz/discord.py) (I assumed this is the correct version) but I still get an error for no module found called discord on start

**Comment by belguawhale** [comment]
Yes, that is the correct version. May I ask what OS you are using and what version of Python you have installed?

**Comment by unreturnable** [comment]
Running of a Debian 8 machine using python 3.6 (not installed from repos)

**Comment by belguawhale** [comment]
Try reinstalling discord.py using `pip install -U discord.py`.

**Comment by unreturnable** [comment]
As far as I can tell the issue seemed to be I was installing the dependencies with pip for python 3.4 as packaged by my system but then running it with python 3.6.

**Comment by belguawhale** [comment]
That seems like a possible cause. Please let me know if the bot works or if there are any more issues.

**Comment by unreturnable** [comment]
Bot seems to work out pretty well. Have a couple of feature requests but I'll make those as separate issues to encourage discussion :smile:
