### ISSUE TITLE
[Help] Role purpose

### ISSUE THREAD

**Issue by PssbleTrngle** [belguawhale/Discord-Werewolf#56]
What is the purpose of the roles _Players_, _Admins_ or _Werewolf Notify_, I can't find any documenation

**Comment by PssbleTrngle** [comment]
Or specifically _Werewolf Notify_, the rest is clear

**Comment by Xinverse** [comment]
The Werewolf Notify role is a self-assignable role that players may choose to give to themselves using a command. It functions similarly to a "Subscribers" role, which server admins could ping to notify players about bigger werewolf games or werewolf related events. It's non-essential for how the games are run by the bot, so you may choose to not create such a role in your server and delete the corresponding code in the codebase. We included it to accommodate people who might want such a feature in their server.

**Comment by PssbleTrngle** [comment]
Ah, thank you!
