### ISSUE TITLE
Bot doesn't start anymore

### ISSUE THREAD

**Issue by marmottin** [belguawhale/Discord-Werewolf#71]
Using the last master version.
Most likely related to the newly pushed API update yesterday.

**Comment by Biggod930416** [comment]
yes, because of API update.

**Comment by Xinverse** [comment]
Hello, I'm one of the maintainers of the bot. We are aware of the issue, and unfortunately the developers of the discord.py library has stopped updating the version of the library that the bot uses. I have put into place a temporary, fixed version of the discord.py library which you can use from now on to run the bot. To do that, run the following commands on your terminal:
`pip3 uninstall discord.py`
`pip3 install -U git+https://github.com/Xinverse/discord.py.git `

This should help get the bot working again.

**Comment by marmottin** [comment]
Confirmed, thanks for the quick fix =)
