### ISSUE TITLE
Cannot connect the bot to Discord

### ISSUE THREAD

**Issue by shiioo** [belguawhale/Discord-Werewolf#8]
I set up the bot on Windows through python v3.5.3 (I have a Debian box but it already has v2.7 & v3.4).

I set up all the IDs in config.py (OWNER_ID, GAME_CHANNEL, DEBUG_CHANNEL, WEREWOLF_SERVER & ADMINS).
Token's also properly set, as roles & channels.

Yet, here's what I get upon launching the bot: `Ignoring exception in on_ready
Traceback (most recent call last):
  File "D:\Python\Python35\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "E:\Discord-Werewolf-master\bot.py", line 74, in on_ready
    await log(1, 'on_ready triggered!')
  File "E:\Discord-Werewolf-master\bot.py", line 1729, in log
    await client.send_message(client.get_channel(DEBUG_CHANNEL), logmsg)
  File "D:\Python\Python35\lib\site-packages\discord\client.py", line 1145, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "D:\Python\Python35\lib\site-packages\discord\client.py", line 289, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType`

I triple-checked all the IDs, yet it still refuses to connect.

**Comment by belguawhale** [comment]
The error would indicate that the debug channel id is incorrect. Are you setting the id as a string? It should look like `DEBUG_CHANNEL = '255531567936569344'`

**Comment by shiioo** [comment]
Yes, that's how all my IDs look, the debug one included.

`GAME_CHANNEL = '300612967085637634'
DEBUG_CHANNEL = '300613088070205450'`

**Comment by belguawhale** [comment]
Hmm, that's strange. Could you pm me on Discord and send me an invite link to your server? I'm also assuming that GAME_CHANNEL and DEBUG_CHANNEL are on different lines in your snippet above.

**Comment by shiioo** [comment]
Thanks for troubleshooting, all good now :)

**Comment by GearExecutor** [comment]
i also have the same problem as shiioo, pretty sure i have set them all right, can u help me pls?

> OWNER_ID = '175567521070448640'
BOT_PREFIX = '!'
TOKEN = 'MzA3NTAzNjY4OTgxMjY4NDgx.C-TQtg.mvarlYlemM906az2TVRPwi79PQ4'
GAME_CHANNEL = '307511129658097674'
DEBUG_CHANNEL = '307509909627338752'
WEREWOLF_SERVER = '179561591329652737'
PLAYERS_ROLE_NAME = 'Players'
ADMINS_ROLE_NAME = 'Admins'
WEREWOLF_NOTIFY_ROLE_NAME = 'Werewolf Notify'
ADMINS = ['175946239676776448','176308506222133248']
IGNORE_LIST = []
TOKENS_GIVEN = 5
TOKEN_RESET = 10
IGNORE_THRESHOLD = 7
NOTIFY_FILE = 'notify.txt'
BACKUP_INTERVAL = 300
MESSAGE_LANGUAGE = 'en'
LOG_FILE = 'debug.txt'
MIN_LOG_LEVEL = 0
STASIS_FILE = 'stasis.json'

**Comment by belguawhale** [comment]
Uhh first of all, you may want to refresh your token since it is posted in a public place and will allow anyone to log in as your bot

**Comment by GearExecutor** [comment]
well yes i can do that

**Comment by belguawhale** [comment]
Second of all, did you add the bot to your server?

**Comment by GearExecutor** [comment]
adding my bot that i have created right?
how to confirm it is added?

**Comment by belguawhale** [comment]
When you run the bot, you should see the bot online in the sidebar on discord.

Can you also please copy and paste the error in console here?

**Comment by GearExecutor** [comment]
ah right, its not there, sry but how to add it?

**Comment by belguawhale** [comment]
Go here: https://discordapi.com/permissions.html#335670288 and copy/paste the bot's id into where it says "Insert Client ID here"

**Comment by GearExecutor** [comment]
ah nvm, it worked, thx!

**Comment by belguawhale** [comment]
Try running a game by joining the game, doing `!fjoin 1-3`, then `!fstart` to make sure all permissions are set up properly (bot can send messages in lobby, in debug channel, bot can assign roles, change lobby channel permissions, and so on)
